language: php
php:
- 5.6
- 7
sudo: false

branches:
  only:
  - master

install:
- nvm install 6

before_script: bash ./.bin/build.sh

script:
- ls -al style.css

after_success: bash ./.bin/deploy.sh

env:
  global:
  - GH_REF: github.com/inc2734/habakiri.git
  - secure: "a/sVsoEwJnsc47RIU5/QjxqcD0+nE8KoS2tvsoU+zVt/MHN8eIgV+TLlPwowW3FGLGIQd1kLJr710Hl9iZ3swdyrf7AempfiM/oj9VNOvBvzJm4IRdWWH9mZYBD8M6S1mvJeRmH2YEpP0ot86tmh3mGwA5YXEtHNqMMCZA3pW2A="
